PDF=com.pstconverter.core.output.handlers.PdfOutputHandler
HTML=com.pstconverter.core.output.handlers.HtmlOutputHandler
MHTML=com.pstconverter.core.output.handlers.MhtmlOutputHandler
TXT=com.pstconverter.core.output.handlers.TxtOutputHandler
RTF=com.pstconverter.core.output.handlers.RtfOutputHandler
DOC=com.pstconverter.core.output.handlers.DocOutputHandler
JSON=com.pstconverter.core.output.handlers.JsonOutputHandler
CSV=com.pstconverter.core.output.handlers.CsvOutputHandler
MBOX=com.pstconverter.core.output.handlers.MboxOutputHandler
EML=com.pstconverter.core.output.handlers.EmlOutputHandler
MSG=com.pstconverter.core.output.handlers.MsgOutputHandler
PST=com.pstconverter.core.output.handlers.PstOutputHandler
EMLX=com.pstconverter.core.output.handlers.EmlxOutputHandler
OFFICE_365=com.pstconverter.core.output.handlers.CloudOutputHandler
GMAIL=com.pstconverter.core.output.handlers.CloudOutputHandler
IMAP=com.pstconverter.core.output.handlers.CloudOutputHandler
YAHOO=com.pstconverter.core.output.handlers.CloudOutputHandler
